### ISSUE TITLE
Inquiry for adversarial training

### ISSUE THREAD

**Issue by ZekunStevenZhang** [BorealisAI/advertorch#11]
Hi, thanks for making this pytorch toolbox, it really helps a lot.

I'm just wondering if there are any adversarial trained models in pytorch? Or will you provide these models in the future?

Thanks again for sharing this wonderful toolbox

**Comment by gwding** [comment]
Hi @ZekunStevenZhang , thanks for your interests! This is an adversarially trained model on MNIST, https://github.com/BorealisAI/advertorch/blob/master/advertorch_examples/trained_models/mnist_lenet5_advtrained.pt with the training script at https://github.com/BorealisAI/advertorch/blob/master/advertorch_examples/tutorial_train_mnist.py

**Comment by ZekunStevenZhang** [comment]
Thanks for the reply!
