### ISSUE TITLE
Expected object of type torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by xinlee2018111** [BorealisAI/advertorch#14]
Hello,

Thanks for the awesome code. I am currently using advertorch to attack my self-trained Densenet with 8 classes. Everything works well for the attack methods without num_classes such as LinfPGDAttack. However when I use any attacks that need num_classes such as CarliniWagnerL2Attack. I got the error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-642ac7d074fe> in <module>
----> 1 advimg = adversary.perturb(image_tensor, label)

~/anaconda3/envs/pytorch04py37/lib/python3.7/site-packages/advertorch/attacks/carlini_wagner.py in perturb(self, x, y)
    224                 loss, l2distsq, output, adv_img = \
    225                     self._forward_and_update_delta(
--> 226                         optimizer, x_atanh, delta, y_onehot, loss_coeffs)
    227                 if self.abort_early:
    228                     if ii % (self.max_iterations // NUM_CHECKS or 1) == 0:

~/anaconda3/envs/pytorch04py37/lib/python3.7/site-packages/advertorch/attacks/carlini_wagner.py in _forward_and_update_delta(self, optimizer, x_atanh, delta, y_onehot, loss_coeffs)
    131         output = self.predict(adv)
    132         l2distsq = calc_l2distsq(adv, transimgs_rescale)
--> 133         loss = self._loss_fn(output, y_onehot, l2distsq, loss_coeffs)
    134         loss.backward()
    135         optimizer.step()

~/anaconda3/envs/pytorch04py37/lib/python3.7/site-packages/advertorch/attacks/carlini_wagner.py in _loss_fn(self, output, y_onehot, l2distsq, const)
    101         loss2 = (l2distsq).sum()
    102         loss1 = torch.sum(const * loss1)
--> 103         loss = loss1 + loss2
    104         return loss
    105 

RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #3 'other'

**Comment by gwding** [comment]
This is a bit hard to debug without actually having access to your code...
Were you able to track down which tensor is the "source" of being "torch.FloatTensor"? as I assume everything should be cuda?
Or if you could make a script reproducing this error, than I can run it and try to locate the problem

**Comment by gwding** [comment]
@xinlee2018111 I'm closing this issue for now. Please reopen if the problem persists.
