### ISSUE TITLE
Multiple inputs of model

### ISSUE THREAD

**Issue by LYF14020510036** [BorealisAI/advertorch#16]
hello, Multiple inputs of model?

ypred= model(data0, data1, data2, data3=data3)

adversary.perturb(？？？？？？？？？？？？)

What should I do?

**Comment by gwding** [comment]
What are the dimensionalities of the these data? can they be concatenated to be a single tensor?

If yes, then you want to define a `predict` function like below and pass it to the adversary

```
def predict(concatenated_data):
    data0, data1, ... = get_single_data_out(concatenated_data)
    return model(data0, data1, data2, data3=data3)
```

However, if each input have different norm constraints, then it's a bit tricky

**Comment by LYF14020510036** [comment]
Thank you very much, different dimensionalities of the these data?This means that I want to find ways to modify the parameters of input of model.

**Comment by gwding** [comment]
I see. Then it seems that this will work, as long as you are able to define the `get_single_data_out` function, which potentially involves resizing tensors.

**Comment by LYF14020510036** [comment]
Thank you very much for your suggestion. I will try to implement it according to your suggestion.
