### ISSUE TITLE
Error loading notebook

### ISSUE THREAD

**Issue by nocotan** [BorealisAI/advertorch#36]
I tried `advertorch_examples/tutorial_attack_defense_bpda_mnist.ipynb`  on the jupyter notebook, but got an error.

```
Unreadable Notebook: 
advertorch/advertorch_examples/tutorial_attack_defense_bpda_mnist.ipynb 
NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')
```

I was able to run `tutorial_attack_imagenet.ipynb` on the jupyter notebook without any problems.

**Comment by gwding** [comment]
Hi @nocotan , sorry for the inconvenience. I just fixed it in the latest master. It seems working fine locally for me and the preview on github seems working too https://github.com/BorealisAI/advertorch/blob/master/advertorch_examples/tutorial_attack_defense_bpda_mnist.ipynb

Let me know if it is resolved on your end :)

**Comment by nocotan** [comment]
@gwding Thank you for your quick response! It seems to work correctly!
