### ISSUE TITLE
question for iterative l2 attack

### ISSUE THREAD

**Issue by ZekunStevenZhang** [BorealisAI/advertorch#39]
I have questions for both l2 PGD attack and Momentum iterative attack methods when compared with cleverhans
as for PGD:
why using 
**_if eps is not None: 
    delta.data = clamp_by_pnorm(delta.data, ord, eps)_**
instead of
**_delta.data = batch_clamp(eps, delta.data)_**
same as for momentum iterative attack?

I thought the iteration step should be:
**delta = clamp[(delta + eps_iter * (pnorm(g))), eps]**
But you are somehow doing a **_clamp_by_pnorm_** operation here. It's quite different from other's implementations. So why are you doing this for l2 attack?

And I followed your settings to run l2-pgd attack on ResNet 50 trained on ImageNet, the attack didn't work at all. But L-inf worked for both PGD and MIFSGM.

**Comment by gwding** [comment]
regarding
```
if eps is not None:
    delta.data = clamp_by_pnorm(delta.data, ord, eps)
```
here we want to project `delta.data` back to the L2-ball with radius `eps`, this cannot be done by `batch_clamp`, which can only be used for projecting delta back to Linf-ball.

The code in https://github.com/BorealisAI/advertorch/blob/master/advertorch/attacks/iterative_projected_gradient.py#L80-L83 is basically doing what you've suggested. 

If you'd like to compare with cleverhans, their `clip_eta` function is basically doing the same thing, https://github.com/tensorflow/cleverhans/blob/51cb6d660b9d333ee637baf595205c7f5d1f1d66/cleverhans/utils_tf.py#L358

**Comment by gwding** [comment]
regarding attacking ResNet 50 on ImageNet, what is the eps for L2 PGD attack? it usually needs to be higher than the value for Linf PGD in order to succeed.

**Comment by ZekunStevenZhang** [comment]
Thanks for ur help, I really appreciate that. Looks like I misunderstood this part. 

By the way, what would be the appropriate parameters for eps when attacking ResNet50 on ImageNet using L2-ball projection?

Thanks again for this toolbox, it's a really great job.

**Comment by gwding** [comment]
@ZekunStevenZhang you're welcome. Usually eps=1 is a good starting point for L2PGDAttack, I've updated https://github.com/BorealisAI/advertorch/blob/master/advertorch_examples/tutorial_attack_imagenet.ipynb to include the L2PGDAttack example there.

**Comment by ZekunStevenZhang** [comment]
Thank you so much, that helps a lot!
