### ISSUE TITLE
Question between two similar attacks

### ISSUE THREAD

**Issue by averyma** [BorealisAI/advertorch#43]
Is it true that L2PGDAttack and L2BasicIterativeAttack are equivalent except L2PGDAttack has the option to change rand_init, whereas rand_init is disabled in the latter one?
(I notice the same pattern in LinfPGDAttack and LinfBasicIterativeAttack)

**Comment by gwding** [comment]
Yes, pretty much. For details/comparisons, see Section 3 at https://openreview.net/pdf?id=rJzIBfZAb and Section 2.2 at https://arxiv.org/pdf/1607.02533.pdf

**Comment by averyma** [comment]
Thanks for the reply.
