### ISSUE TITLE
L1 PGD attack issue

### ISSUE THREAD

**Issue by Kimtic** [BorealisAI/advertorch#48]
Hello! I got the following errors when trying to use L1PGD attacks

.local/lib/python3.6/site-packages/advertorch/attacks/utils.py", line 56, in rand_init_delta
    delta.data = clamp(x.data + delta.data, clip_min, clip_max) - x.data
RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

So, I changed the line 55 and 62 from delta.data to delta.data.cuda(), and it worked. But I do not know why when I was using other L2, and LInf PGD attacks there were no such issues. Can I use L2 and LInf with this change?

Thank you!

**Comment by gwding** [comment]
Sorry about the inconvenience! 
Your change shouldn't affect the correctness of L2/Linf attack.

`delta` is supposed to have the same data type/device as `x` at the beginning of `rand_init_delta()`, so in the L1 case, it must be overwritten somehow. I'll reply below once I fix the problem. Thanks again for reporting.

**Comment by Kimtic** [comment]
Thank you!!

Best,
Jungeum

2019년 10월 15일 화요일, Gavin Weiguang Ding <notifications@github.com>님이 작성:

**Comment by shijianjian** [comment]
Hi @gwding,

I think there are still some problems with L1 PGD attack. Here is the stack trace:

```
~/anaconda3/envs/torch1.2/lib/python3.7/site-packages/advertorch/attacks/iterative_projected_gradient.py in perturb_iterative(xvar, yvar, predict, nb_iter, eps, eps_iter, loss_fn, delta_init, minimize, ord, clip_min, clip_max, l1_sparsity)
    107             delta.data = delta.data + batch_multiply(eps_iter, grad)
    108 
--> 109             delta.data = batch_l1_proj(delta.data.cpu(), eps)
    110             if xvar.is_cuda:
    111                 delta.data = delta.data.cuda()

~/anaconda3/envs/torch1.2/lib/python3.7/site-packages/advertorch/utils.py in batch_l1_proj(x, eps)
    250     batch_size = x.size(0)
    251     view = x.view(batch_size, -1)
--> 252     proj_flat = batch_l1_proj_flat(view, z=eps)
    253     return proj_flat.view_as(x)
    254 

~/anaconda3/envs/torch1.2/lib/python3.7/site-packages/advertorch/utils.py in batch_l1_proj_flat(x, z)
    237     st = (mu.cumsum(1) - z) / (vv + 1)
    238     u = (mu - st) > 0
--> 239     rho = (1 - u).cumsum(dim=1).eq(0).sum(1) - 1
    240     theta = st.gather(1, rho.unsqueeze(1))
    241     proj_x_b = _thresh_by_magnitude(theta, x_b)

~/anaconda3/envs/torch1.2/lib/python3.7/site-packages/torch/tensor.py in __rsub__(self, other)
    392 
    393     def __rsub__(self, other):
--> 394         return _C._VariableFunctions.rsub(self, other)
    395 
    396     def __rdiv__(self, other):

RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.
```

My settings:
```python
{'eps': 0.18104110658168793, 'nb_iter': 10, 'eps_iter': 0.013909362256526947, 'clip_min': 0, 'clip_max': 1, 'rand_init': True, 'ord': 1, 'l1_sparsity': None, 'targeted': True}
x = torch.randn(32, 3, 299, 299)
y = tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
```

**Comment by gwding** [comment]
@shijianjian Thanks for bringing this up. I was working on fixing this but hasn't finished. 
See this quick fix here, https://github.com/BorealisAI/advertorch/pull/59/files
My impression is that if I changed it, then previous pytorch version will give me error/warnings.
For now, changing `1-u` to `~u` should probably work for you.
I'll get this merged into master after resolving different behaviors under different versions.

**Comment by gwding** [comment]
see https://github.com/BorealisAI/advertorch/pull/59

**Comment by shijianjian** [comment]
Hi @grwding,

If the param ```u``` is always bool, ```(1 - u.int()).sign().to(torch.bool)``` should work.

**Comment by gwding** [comment]
fixed in https://github.com/BorealisAI/advertorch/pull/78, closing
