### ISSUE TITLE
FGSM return tensor cannot compute the gradient

### ISSUE THREAD

**Issue by xunge** [BorealisAI/advertorch#49]
I want to get the fgsm_tensor.grad().clone() but got the problem about 

> "AttributeError: 'NoneType' object has no attribute 'clone'".

However, PGD doesn't have this problem.

I find that fgsm_tensor.is_leaf is False, so that can not compute the gradient.

In this line, [one_step_gradient.py#L71](https://github.com/BorealisAI/advertorch/blob/40d6386640a2b973c992f3a83c72ce6ea2460268/advertorch/attacks/one_step_gradient.py#L71) xadv.is_leaf become False.

Maybe you can change `return xadv` to `return xadv.detach()` to fix this problem, but I don't confirm that if it is necessary.

**Comment by gwding** [comment]
Hi :)
what is fgsm_tensor in the code? is it x_adv?
do you want to change the code to suit your needs and make a pull request?

**Comment by xunge** [comment]
Yes, fgsm_tensor is x_adv generate from FGSM attack method.
The code don't have to change because it is not a bug in this project, just a strange feature in pytorch. So I won't make a pull request, thanks.
