### ISSUE TITLE
Targeted attacks increases accuracy to 100%

### ISSUE THREAD

**Issue by awaisrauf** [BorealisAI/advertorch#55]
If we use targeted attacks option in many attacks, it increases the accuracy of network to almost 100% which is very strange. I have observed this in cifar10, 100 and imagenet. Here is one examlpe. 
![image](https://user-images.githubusercontent.com/30290500/71861895-50674c80-313b-11ea-93ee-f4267326a5ad.png)

**Comment by gwding** [comment]
Hi @awaisrauf , one possibility I can speculate is that, if you still give it the true label and ask it to do targeted attack, then it actually tries to perturb the prediction to be the true label, therefore the accuracy is close to 100%.

**Comment by awaisrauf** [comment]
Right. Thanks. 
But how do we choose the targeted class if we are trying to evaluate on a larger dataset like imagenet? Is making targeted class random okay?

**Comment by feinsteinben** [comment]
It really depends on what you want to demonstrate. The common approach is to select a target label at random (from the set incorrect labels). Another approach is to choose the least-scored label (w.r.t the predictions on the clean image).
