### ISSUE TITLE
Best way to constrain CarliniWagnerL2Attack on epsilon

### ISSUE THREAD

**Issue by linzzzzzz** [BorealisAI/advertorch#65]
This is more a question than an issue. I'm just wondering what's the best way to put constraints on CarliniWagnerL2Attack so that the perturbation is within a norm epsilon-ball?

Thanks.

**Comment by gwding** [comment]
Do you want a Linf ball or a general norm ball?
Linf ball is easier to implement than others, e.g. L2 balls.

One way is to utilize that the `arctanh` is calculated adaptively based `clip_min/max`, and set different `clip_min/max` based on your input for each examples.

Another way is to preprocess (some linear scaling) your data first, such that your Linf ball is mapped the unit cube. Then after the attack, apply the inverse mapping.

**Comment by linzzzzzz** [comment]
Thanks for the quick reply!

Correct me if I'm wrong.. Since I'm trying to use CarliniWagnerL2Attack, it only makes sense to enforce a L2 ball right?

Also I assumed what you said was about enforcing a Linf ball and they all make sense to me. Thanks :)

Might be a separate question.. I was reading your MMA paper and saw you mentioned doing experiments using **CW-PGD** attacks. I also saw the term **PGD attack using CW loss** in cifar10_challenge from Madry lab. I'm kind of wondering what's the difference between **CW-PGD** attack and CarliniWagnerL2Attack in this case? Is this type of **CW-PGD** attack implementable through advertorch?

Best

**Comment by gwding** [comment]
`CarliniWagnerL2Attack` is trying to find a successful attack with minimum L2 norm. So you don't really "enforce" a L2 ball. You can enforce any local neighborhood and then perform it.

CW-PGD attack can be implemented by just setting the loss to be the cw loss in the PGD attack in advertorch like
```
LinfPGDAttack(..., loss=CWLoss(reduction="sum"), ...)
```

A CWLoss implementation will soon be merged in this PR https://github.com/BorealisAI/advertorch/pull/64/files

**Comment by linzzzzzz** [comment]
Got it. Great to know that CWLoss implementation is right around the corner :)

Looking at the implementation of CWLoss, I'm having a little bit hard time understanding the connection between **PGD with CWLoss** and **CarliniWagnerL2Attack**. 

Correct me if I'm wrong, my impression is that **CarliniWagnerL2Attack** and **PGD with CWLoss** are related but different.

**CarliniWagnerL2Attack** is trying to explicitly minimize the loss 

![image](https://user-images.githubusercontent.com/16128320/75645122-c0152780-5c12-11ea-8f07-062e29642461.png)

**PGD with CWLoss** is pretty much doing the same thing but through a different way: iteratively going to the CWLoss gradient sign direction.

I'm kind of new to this field but just curious:
- When evaluating the adversarial robustness of a model against C&W attack, is either of this two attacks a more preferred practice?

Thank you again for your time and really appreciate it!

**Comment by gwding** [comment]
I think your understanding is correct.
I haven't done a systematic comparison between CW attack and PGD attack when they are under the same Lp norm, and I'm not aware of any at this moment. But historically, CW is usually for L2 and PGD is usually for Linf.

**Comment by linzzzzzz** [comment]
Cool. Appreciated it!
