### ISSUE TITLE
About “To install the package in "editable" mode”

### ISSUE THREAD

**Issue by TTTJJJWWW** [BorealisAI/advertorch#77]
Hi,
The "editable" mode means that i can modify the source code of advertorch for my research？
And how can i save the change on advertorch？ By running “ pip install -e ." again?

thanks!

**Comment by gwding** [comment]
After you install with `pip install -e .`, you can modify advertorch code inplace and it'll be reflected in the module after you import it again. I would suggest try adding some print statement in advertorch code you want to modify to verify this.
