### ISSUE TITLE
Is it possible to implement the MomentumIterativeAttack to L2

### ISSUE THREAD

**Issue by xunge** [BorealisAI/advertorch#9]
Is it possible to implement the MomentumIterativeAttack to L2? Just like the PGDAttack which both has the Linf and L2. Thanks for your reply.

**Comment by gwding** [comment]
@xunge thanks for your interest. it is on our to do list, and if things go well, it could be available sometime next week.

**Comment by xunge** [comment]
Thank you very much. This project helps me a lot~

**Comment by gwding** [comment]
@xunge Have a look at PR #10 for now. It might take some time to merge that branch into master, but the current version should work well.
