### ISSUE TITLE
name 'adversary' is not defined

### ISSUE THREAD

**Issue by YOONAHLEE** [BorealisAI/advertorch#90]
Hello,
I used this library well until now... and a weird problem happened.

`name 'adverary' is not defined`

from second data batch loop, that error comes out...
It is weird because If it is not defined, than how it works in first batch ?

`
adversary = LinfPGDAttack(
        base_net, loss_fn=nn.CrossEntropyLoss(reduction="sum"),
        eps=8/255., nb_iter=50, eps_iter=2/255., rand_init=True,
        clip_min=0.0, clip_max=1.0, targeted=False
        )
def adversarial_test(test_loader, net, adversary):
    
    net.eval()
    test_loss = test_acc = 0
    iterator = tqdm(test_loader)
    print(adversary) # it is printed well.  <advertorch.attacks.iterative_projected_gradient~

    for data, target in iterator:
        
        data, target = data.cuda(), target.cuda()
        adv = adverary.perturb(data,target)
        output = net(adv)

`

**Comment by masoudhashemi** [comment]
Hi, seems you have a typo at `adv = adverary.perturb(data,target)`

**Comment by YOONAHLEE** [comment]
Oh I am sorry.
yes it was just a type.
