### ISSUE TITLE
Problem that pytorch v1.9.0 is not supported

### ISSUE THREAD

**Issue by MasanoriYamada** [BorealisAI/advertorch#91]
Advertorch uses the deprecated function torch.autograd.gradcheck.zero_gradients().
This function is no longer available in v1.9.0, so Advertorch will not work.

torch  
v1.8.1: https://github.com/pytorch/pytorch/blob/v1.8.1/torch/autograd/gradcheck.py#L12
v.1.9.0https://github.com/pytorch/pytorch/blob/v1.9.0/torch/autograd/gradcheck.py

**Comment by Asber777** [comment]
I meet the same problem, so I decide to change my torch version.
Wish the developer can solve it asap

**Comment by mcgradymvp** [comment]
I think the latest commit #93 has fixed the issue. I installed using `python setup.py install`

**Comment by Asber777** [comment]
> I think the latest commit #93 has fixed the issue. I installed using `python setup.py install`

thank you. I used the pip way, and work by your advice.
